keys:
  - &admin_local age1sur65t9wa9s0krds32kx9h379masmkyf663wwwav2ye0v5syyv2qkaxsd8
  - &server_gce "age1..."  # REPLACE

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *admin_local
          - *server_gce
