version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          kotlin-and-kotlinx:
              patterns:
                  - "org.jetbrains.kotlin*"
                  - "org.jetbrains.kotlinx*"
              update-types:
                  - "minor"
                  - "patch"
